# This workflow will run the pana score on the latest commit to a pull request
name: pana_score
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  build:
    uses: atsign-foundation/.github/blob/pana-pr/workflows/pana_pr_workflow.yml
    
