include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    annotate_overrides: error
    dead_code: warning
    todo: ignore
    unawaited_futures: error
    await_only_futures: error
    unnecessary_await_in_return: info

linter:
  rules:
    prefer_relative_imports: true
    annotate_overrides: true
    unawaited_futures: true
    await_only_futures: true
    